version: '3'

services:
  postservice:
    container_name: postService
    build:
      context: .
      dockerfile: PostService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports: 
      - "5000:5000"
  userservice:
    container_name: userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    ports: 
      - "5001:5001"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
   